# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.0

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia
      script:
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
        - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
