language: julia
os:
  - linux
julia:
#  - release
  - nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'Pkg.add("JLD")'
  - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("Hanja"); Pkg.test("Hanja"; coverage=true)'
after_success:
  - julia --color=yes -e 'if VERSION >= v"0.4-"; cd(Pkg.dir("Hanja")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); end'
